"""update datachunk

Revision ID: 3219e1ffe304
Revises: 2d8db4d71734
Create Date: 2025-09-02 01:11:48.636597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3219e1ffe304'
down_revision: Union[str, Sequence[str], None] = '2d8db4d71734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('text', sa.String(), nullable=False))
    op.add_column('chunks', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('chunks', sa.Column('order', sa.Integer(), nullable=False))
    op.drop_column('chunks', 'chunk_order')
    op.drop_column('chunks', 'chunk_metadata')
    op.drop_column('chunks', 'chunk_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chunks', sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('chunks', sa.Column('chunk_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('chunks', 'order')
    op.drop_column('chunks', 'meta')
    op.drop_column('chunks', 'text')
    # ### end Alembic commands ###
